<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Web\Base64DecoderController;
use App\Http\Controllers\Web\Base64EncoderController;
use App\Http\Controllers\Web\ImageToBase64Controller;
use App\Http\Controllers\Web\WhatsappLinkGeneratorController;
use App\Http\Controllers\Api\BackgroundRemoverApiController;
use App\Http\Controllers\Api\ColorFeedbackController;
use App\Http\Controllers\Web\BackgroundRemoverController;
use App\Http\Controllers\Web\ImageCompressorController;
use App\Http\Controllers\Api\WebpToPngSimpleController;
use App\Http\Controllers\Web\HtmlToTextController;
use App\Http\Controllers\Web\CssFormatterController;
use App\Http\Controllers\Web\HtmlFormatterController;
use App\Http\Controllers\Web\XmlFormatterController;
use App\Http\Controllers\Web\JsonFormatterController;
use App\Http\Controllers\Web\JavascriptFormatterController;
use App\Http\Controllers\Web\JsonToArrayController;
use App\Http\Controllers\Web\CountryLibraryController;
use App\Http\Controllers\Web\ColorPaletteController;
use App\Http\Controllers\Web\EmojiLibraryController;
use App\Http\Controllers\Web\ImageResizerController;
use App\Http\Controllers\Api\WebpToPngApiController;
use App\Http\Controllers\Api\WatermarkApiController;
use App\Http\Controllers\Api\FaviconsApiController;
use App\Http\Controllers\Web\WebpToPngController;
use App\Http\Controllers\Web\WatermarkController;
use App\Http\Controllers\Web\FaviconsController;
use App\Http\Controllers\Web\SitemapController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\WordCounterController;
use App\Http\Controllers\Web\LoremGeneratorController;
use App\Http\Controllers\Web\QrGeneratorController;
use App\Http\Controllers\Web\BarcodeGeneratorController;
use App\Http\Controllers\Web\TextAnalyzerController;
use App\Http\Controllers\Web\AiWebsiteDetectorController;
use App\Http\Controllers\Web\SeoOptimizerCheckerController;
use App\Http\Controllers\Web\PageNotFoundController;
use App\Http\Controllers\Web\SeoHeadingStructureController;
use App\Http\Controllers\Api\SeoAnalyzerApiController;
use App\Http\Controllers\Api\SeoHeadingStructureApiController;
use App\Http\Controllers\Api\AiWebsiteDetectorApiController;
use App\Http\Controllers\Web\IpInfoController;
use App\Http\Controllers\Api\IpInfoApiController;

Route::get('/biblioteca-paises-mundo', [CountryLibraryController::class, 'index'])->name('tools.country-library');
Route::get('/biblioteca-emojis', [EmojiLibraryController::class, 'index'])->name('tools.emoji-library');
Route::get('/generador-links-whatsapp', [WhatsappLinkGeneratorController::class, 'index'])->name('tools.whatsapp-link-generator');
Route::get('/convertir-html-a-texto', [HtmlToTextController::class, 'index'])->name('tools.html-to-text');
Route::get('/codificar-base64-online', [Base64EncoderController::class, 'index'])->name('tools.base64-encoder');
Route::get('/decodificar-base64-online', [Base64DecoderController::class, 'index'])->name('tools.base64-decoder');
Route::get('/convertir-imagen-base64-online', [ImageToBase64Controller::class, 'index'])->name('tools.image-to-base64');
Route::get('/formatear-html-online', [HtmlFormatterController::class, 'index'])->name('tools.html-formatter');
Route::get('/formatear-css-online', [CssFormatterController::class, 'index'])->name('tools.css-formatter');
Route::get('/formatear-xml-online', [XmlFormatterController::class, 'index'])->name('tools.xml-formatter');
Route::get('/formatear-json-online', [JsonFormatterController::class, 'index'])->name('tools.json-formatter');
Route::get('/formatear-javascript-online', [JavascriptFormatterController::class, 'index'])->name('tools.javascript-formatter');
Route::get('/convertir-json-a-array', [JsonToArrayController::class, 'index'])->name('tools.json-to-array');
Route::get('/generador-favicons-online', [FaviconsController::class, 'index'])->name('tools.favicons');
Route::post('/api/tools/favicons', [FaviconsApiController::class, 'generate'])->name('api.tools.favicons');
Route::get('/sitemap.xml', [SitemapController::class, 'index'])->name('sitemap');
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/comprimir-imagenes-online-gratis', [ImageCompressorController::class, 'index'])->name('tools.image-compressor');
Route::get('/quitar-fondo-imagen-gratis', [BackgroundRemoverController::class, 'index'])->name('tools.background-remover');
Route::post('/api/tools/background-remover', [BackgroundRemoverApiController::class, 'process'])->name('api.tools.background-remover');
Route::get('/redimensionar-imagenes-online-gratis', [ImageResizerController::class, 'index'])->name('tools.image-resizer');
Route::get('/convertidor-imagenes-universal', [WebpToPngController::class, 'index'])->name('tools.webp-to-png');
Route::post('/api/tools/webp-to-png', [WebpToPngApiController::class, 'process'])->name('api.tools.webp-to-png');
Route::post('/webp-to-png', [WebpToPngSimpleController::class, 'convert'])->name('webp.to.png');
Route::get('/poner-marca-de-agua-imagen-gratis', [WatermarkController::class, 'index'])->name('tools.watermark');
Route::post('/api/tools/watermark', [WatermarkApiController::class, 'process'])->name('api.tools.watermark');
Route::get('/contador-palabras-caracteres-online', [WordCounterController::class, 'index'])->name('tools.word-counter');
Route::get('/generador-texto-lorem-ipsum', [LoremGeneratorController::class, 'index'])->name('tools.lorem-generator');
Route::get('/generador-codigo-qr-online', [QrGeneratorController::class, 'index'])->name('tools.qr-generator');
Route::get('/generador-codigo-barras-online', [BarcodeGeneratorController::class, 'index'])->name('tools.barcode-generator');
Route::get('/paleta-de-colores-online', [ColorPaletteController::class, 'index'])->name('tools.color-palette');
Route::get('/analizador-texto-ia', [TextAnalyzerController::class, 'index'])->name('tools.text-analyzer');
Route::get('/detector-pagina-web-ia', [AiWebsiteDetectorController::class, 'index'])->name('tools.ai-website-detector');
Route::get('/analizador-seo-url', [SeoOptimizerCheckerController::class, 'index'])->name('tools.seo-optimizer-checker');
Route::post('/api/tools/seo-analyzer', [SeoAnalyzerApiController::class, 'analyze'])->name('api.tools.seo-analyzer');
Route::get('/analizador-estructura-titulos', [SeoHeadingStructureController::class, 'index'])->name('tools.seo-heading-structure');
Route::post('/api/tools/seo-heading-structure', [SeoHeadingStructureApiController::class, 'analyze'])->name('api.tools.seo-heading-structure');
Route::post('/api/tools/ai-website-detector', [AiWebsiteDetectorApiController::class, 'analyze'])->name('api.tools.ai-website-detector');
Route::post('/api/tools/color-feedback', [ColorFeedbackController::class, 'send'])->name('api.tools.color-feedback');
Route::get('/cual-es-mi-ip-publica', [IpInfoController::class, 'index'])->name('tools.ip-info');
Route::get('/api/tools/ip-info', [IpInfoApiController::class, 'show'])->name('api.tools.ip-info');

Route::fallback([PageNotFoundController::class, '__invoke']);
